name: Coding Standards

on:

    push:
        branches:
            - main

    pull_request:

    schedule:
        - cron: '20 16 * * SUN'

jobs:

    php-cs-fixer:

        name: PHP Coding Standards
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  tools: php-cs-fixer:3, cs2pr

            - name: Create var/ directory
              run: mkdir var

            - name: Cache PHP Coding Standards
              uses: actions/cache@v2
              with:
                  path: var/.php_cs.cache
                  key: php-cs-fixer-${{ github.sha }}
                  restore-keys: php-cs-fixer-

            - name: Run PHP Coding Standards
              run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
