name: PHPUnit

on:

    push:
        branches:
            - main

    pull_request:

    schedule:
        - cron: '20 16 * * SUN'

jobs:

    phpunit:

        name: DD ${{ matrix.dd }} SF ${{ matrix.sf }} PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.is_next }}

        strategy:
            matrix:
                include:
                    - { dd: '6.1.*', sf: '5.4.*', php: '8.1', is_next: false }
                    - { dd: '6.1.*', sf: '6.4.*', php: '8.2', is_next: false }
                    - { dd: '6.1.*', sf: '7.0.*', php: '8.3', is_next: false }

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Require specific dependencies versions
              run: composer require -w matomo/device-detector:${{ matrix.dd }} symfony/framework-bundle:${{ matrix.sf }}

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2

            - name: Run PHPUnit
              run: vendor/bin/phpunit
