name: Static Analysis

on:

    push:
        branches:
            - main

    pull_request:

    schedule:
        - cron: '20 16 * * SUN'

jobs:

    phpstan:

        name: PHP Static Analysis
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  tools: phpstan:1, cs2pr

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v1

            - name: Cache PHPStan
              uses: actions/cache@v2
              with:
                  path: var/phpstan/
                  key: phpstan-${{ github.sha }}
                  restore-keys: phpstan-

            - name: Run PHP Static Analysis
              run: phpstan analyse --no-progress --error-format=checkstyle | cs2pr
