name: Tests

on:

    push:
        branches:
            - main

    pull_request:

jobs:

    phpunit:

        name: PHPUnit (P ${{ matrix.php-version }}, D ${{ matrix.device-detector-version }}, S ${{ matrix.symfony-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.0'
                      device-detector-version: '3.9.*'
                      symfony-version: '3.4.*'
                    - php-version: '7.1'
                      device-detector-version: '^3.9'
                      symfony-version: '4.0.*'
                    - php-version: '7.2'
                      device-detector-version: '4.0.*'
                      symfony-version: '^4.0'
                    - php-version: '7.3'
                      device-detector-version: '^4.0'
                      symfony-version: '5.0.*'
                    - php-version: '7.4'
                      device-detector-version: '^4.0'
                      symfony-version: '^5.0'
                      coverage: true
                    - php-version: '8.0'
                      device-detector-version: '^4.0'
                      symfony-version: '^5.0'

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: ${{ matrix.coverage && 'pcov' || 'none' }}

            - name: Get Composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Composer dependencies
              run: |
                  composer update --no-progress --prefer-dist --optimize-autoloader \
                      --with matomo/device-detector:${{ matrix.device-detector-version }} \
                      --with symfony/framework-bundle:${{ matrix.symfony-version }}

            - name: Run PHPUnit
              run: vendor/bin/phpunit --testdox
