name: Tests

on:

    push:
        branches:
            - main

    pull_request:

    schedule:
        - cron: '20 16 * * SUN'

jobs:

    phpunit:

        name: PHPUnit (P ${{ matrix.php-version }}, D ${{ matrix.dd-version }}, S ${{ matrix.sf-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { dd-version: '3.9.*', sf-version: '3.4.*', php-version: '7.0' }
                    - { dd-version: '^3.9',  sf-version: '^3.4',  php-version: '7.1' }
                    - { dd-version: '4.0.*', sf-version: '4.0.*', php-version: '7.2' }
                    - { dd-version: '^4.0',  sf-version: '^4.0',  php-version: '7.3' }
                    - { dd-version: '4.0.*', sf-version: '5.0.*', php-version: '7.4' }
                    - { dd-version: '^4.0',  sf-version: '^5.0',  php-version: '8.0', coverage: true }
                    - { dd-version: '4.0.*', sf-version: '6.0.*', php-version: '8.0' }
                    - { dd-version: '^4.0',  sf-version: '^6.0',  php-version: '8.1' }

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: ${{ matrix.coverage && 'pcov' || 'none' }}

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: highest
                  composer-options: >
                    --with matomo/device-detector:${{ matrix.dd-version }}
                    --with symfony/framework-bundle:${{ matrix.sf-version }}

            - name: Run PHPUnit
              run: vendor/bin/phpunit --testdox ${{ matrix.coverage && '--coverage-clover coverage.xml' || '--no-coverage' }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              if: ${{ matrix.coverage }}
              with:
                  file: ./coverage.xml
