name: Tests

on:

    push:
        branches:
            - main

    pull_request:

jobs:

    phpunit:

        name: PHPUnit (P ${{ matrix.php-version }}, D ${{ matrix.device-detector-version }}, S ${{ matrix.symfony-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.0'
                      device-detector-version: '3.9.*'
                      symfony-version: '3.4.*'
                    - php-version: '7.1'
                      device-detector-version: '^3.9'
                      symfony-version: '4.0.*'
                    - php-version: '7.2'
                      device-detector-version: '4.0.*'
                      symfony-version: '^4.0'
                    - php-version: '7.3'
                      device-detector-version: '^4.0'
                      symfony-version: '5.0.*'
                    - php-version: '7.4'
                      device-detector-version: '^4.0'
                      symfony-version: '^5.0'
                      coverage: true
                    - php-version: '8.0'
                      device-detector-version: '^4.0'
                      symfony-version: '^5.0'

        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: ${{ matrix.coverage && 'pcov' || 'none' }}

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: highest
                  composer-options: >
                    --with matomo/device-detector:${{ matrix.device-detector-version }}
                    --with symfony/framework-bundle:${{ matrix.symfony-version }}

            - name: Run PHPUnit
              run: vendor/bin/phpunit --testdox ${{ matrix.coverage && '--coverage-clover coverage.xml' || '--no-coverage' }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              if: ${{ matrix.coverage }}
              with:
                  file: ./coverage.xml
